-- Capa Bronce (ARQUI1.CAPA_BRONCE): registros + formato + columnas con tipos.
-- CSV  = Kaggle curado. JSON = transaccional/API via Airbyte.
SELECT T.TABLE_NAME AS TABLA,
       T.ROW_COUNT AS REGISTROS,
       CASE WHEN T.TABLE_NAME IN ('AGRICULTURA_CAMPANA', 'COMERCIO_CONTEXTO_MENSUAL', 'PRECIOS_ENSO_MENSUAL',
                                  'EXPORTACIONES_MENSUALES', 'OPERACION_SEMANAL_PG', 'PRECIOS_MENSUALES',
                                  'CALIDAD_RECEPCIONES', 'CLIMA_SUPERVISADO', 'SENSORES_SILOS')
            THEN 'CSV' ELSE 'JSON' END AS FORMATO,
       LISTAGG(C.COLUMN_NAME || ' ' || C.DATA_TYPE, ', ') WITHIN GROUP (ORDER BY C.ORDINAL_POSITION) AS COLUMNAS_TIPOS
FROM ARQUI1.INFORMATION_SCHEMA.TABLES T
JOIN ARQUI1.INFORMATION_SCHEMA.COLUMNS C
  ON C.TABLE_SCHEMA = T.TABLE_SCHEMA AND C.TABLE_NAME = T.TABLE_NAME
WHERE T.TABLE_SCHEMA = 'CAPA_BRONCE' AND T.TABLE_TYPE = 'BASE TABLE'
GROUP BY T.TABLE_NAME, T.ROW_COUNT
ORDER BY REGISTROS DESC;
