-- Conteo por tabla en ARQUI1.CAPA_BRONCE + formato de origen.
-- CSV  = Kaggle curado (Econometria/Forecasting/ML). JSON = transaccional/API via Airbyte.
SELECT TABLE_NAME AS TABLA,
       ROW_COUNT AS REGISTROS,
       CASE WHEN TABLE_NAME IN ('AGRICULTURA_CAMPANA', 'COMERCIO_CONTEXTO_MENSUAL', 'PRECIOS_ENSO_MENSUAL',
                                'EXPORTACIONES_MENSUALES', 'OPERACION_SEMANAL_PG', 'PRECIOS_MENSUALES',
                                'CALIDAD_RECEPCIONES', 'CLIMA_SUPERVISADO', 'SENSORES_SILOS')
            THEN 'CSV' ELSE 'JSON' END AS FORMATO
FROM ARQUI1.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CAPA_BRONCE' AND TABLE_TYPE = 'BASE TABLE'
ORDER BY REGISTROS DESC;
