-- Features por recepcion para fraude en bascula (score 0-100 + tipologias).
-- Incluye: pesos, contrato, n° analisis de laboratorio via asignacion->lote.
SELECT r.ID_RECEPCION, r.FECHA_HORA, r.ID_SILO, r.ID_CONTRATO,
       r.PESO_BRUTO_TN, r.TARA_TN, r.HUMEDAD_PCT, r.IMPUREZAS_PCT,
       r.CALIDAD_GRANO, r.NUMERO_REMISION,
       c.ID_PRODUCTOR, c.PRECIO_ACORDADO_USD_TN, c.VOLUMEN_COMPROMETIDO_TN, c.PRECIO_REFERENCIA_CBOT,
       COALESCE(lab.N_LAB, 0) AS N_LAB
FROM AIRBYTE_DATABASE.BRONCE.RECEPCION_GRANO r
LEFT JOIN AIRBYTE_DATABASE.BRONCE.CONTRATO_COMPRA c ON r.ID_CONTRATO = c.ID_CONTRATO
LEFT JOIN (SELECT a.ID_RECEPCION, COUNT(*) AS N_LAB
           FROM AIRBYTE_DATABASE.BRONCE.ASIGNACION_GRANO a
           JOIN AIRBYTE_DATABASE.BRONCE.CONTROL_CALIDAD q ON q.ID_LOTE = a.ID_LOTE
           GROUP BY 1) lab ON lab.ID_RECEPCION = r.ID_RECEPCION;
