-- Features v2 por productor: volumen + DISPERSION de calidad (std, max, % eventos criticos).
-- v1 solo separaba por tamano (medias identicas). Cuarentena: ID 525 (registro imposible).
SELECT p.ID_PRODUCTOR, p.NOMBRE_COMPLETO, p.TIPO_PRODUCTOR, p.MUNICIPIO, p.AREA_TOTAL_HA,
       COUNT(*) AS N_RECEPCIONES,
       SUM(f.PESO_NETO_TN) AS VOLUMEN_TOTAL_TN,
       AVG(f.PESO_NETO_TN) AS TICKET_MEDIO_TN,
       SUM(COALESCE(f.MERMA_HUMEDAD_TN,0)+COALESCE(f.MERMA_IMPUREZA_TN,0)) AS MERMA_TOTAL_TN,
       AVG(f.HUMEDAD_PCT) AS HUMEDAD_MEDIA, STDDEV(f.HUMEDAD_PCT) AS HUMEDAD_STD, MAX(f.HUMEDAD_PCT) AS HUMEDAD_MAX,
       AVG(CASE WHEN f.HUMEDAD_PCT > 14 THEN 1.0 ELSE 0.0 END) AS PCT_HUM_CRIT,
       AVG(f.IMPUREZAS_PCT) AS IMPUREZAS_MEDIA, STDDEV(f.IMPUREZAS_PCT) AS IMPUREZAS_STD, MAX(f.IMPUREZAS_PCT) AS IMPUREZAS_MAX,
       AVG(CASE WHEN f.IMPUREZAS_PCT > 1 THEN 1.0 ELSE 0.0 END) AS PCT_IMP_CRIT,
       AVG(f.PROTEINA_PCT) AS PROTEINA_MEDIA, AVG(f.ACEITE_PCT) AS ACEITE_MEDIA,
       AVG(CASE WHEN f.CALIDAD_GRANO = 'DESCUENTO' THEN 1.0 ELSE 0.0 END) AS PCT_DESCUENTO,
       MAX(COALESCE(f.MERMA_HUMEDAD_TN,0)+COALESCE(f.MERMA_IMPUREZA_TN,0)) AS MAX_MERMA_EVENTO,
       COUNT(DISTINCT f.SILO_SK) AS N_SILOS
FROM AIRBYTE_DATABASE.ORO.FACT_RECEPCION_GRANO f
JOIN AIRBYTE_DATABASE.ORO.DIM_PRODUCTOR p ON f.PRODUCTOR_SK = p.PRODUCTOR_SK
GROUP BY 1,2,3,4,5 ORDER BY 1;
