-- Features por productor desde Oro (segmentacion k-means + DBSCAN).
-- Grano: 1 fila = 1 productor con recepciones.
SELECT p.ID_PRODUCTOR, p.NOMBRE_COMPLETO, p.TIPO_PRODUCTOR, p.MUNICIPIO, p.DEPARTAMENTO,
       p.AREA_TOTAL_HA, p.CULTIVO_PRINCIPAL,
       COUNT(*) AS N_RECEPCIONES,
       SUM(f.PESO_NETO_TN) AS VOLUMEN_TOTAL_TN,
       AVG(f.PESO_NETO_TN) AS TICKET_MEDIO_TN,
       SUM(COALESCE(f.MERMA_HUMEDAD_TN,0) + COALESCE(f.MERMA_IMPUREZA_TN,0)) AS MERMA_TOTAL_TN,
       AVG(f.HUMEDAD_PCT) AS HUMEDAD_MEDIA,
       AVG(f.IMPUREZAS_PCT) AS IMPUREZAS_MEDIA,
       AVG(f.PROTEINA_PCT) AS PROTEINA_MEDIA,
       AVG(f.ACEITE_PCT) AS ACEITE_MEDIA,
       AVG(CASE WHEN f.CALIDAD_GRANO = 'DESCUENTO' THEN 1.0 ELSE 0.0 END) AS PCT_DESCUENTO,
       COUNT(DISTINCT f.SILO_SK) AS N_SILOS
FROM AIRBYTE_DATABASE.ORO.FACT_RECEPCION_GRANO f
JOIN AIRBYTE_DATABASE.ORO.DIM_PRODUCTOR p ON f.PRODUCTOR_SK = p.PRODUCTOR_SK
GROUP BY 1,2,3,4,5,6,7
ORDER BY 1;
